<a href="https://colab.research.google.com/github/shubhs777c/python-practice/blob/main/numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [8]:
# code
import numpy as np
a = np.random.randint(50,65,15)
a

array([58, 50, 59, 50, 53, 52, 56, 58, 55, 61, 59, 61, 55, 61, 61])

In [6]:
b = np.random.randint(25,75,24).reshape(6,4)
b

array([[68, 38, 58, 73],
       [30, 41, 25, 61],
       [53, 64, 35, 70],
       [48, 41, 43, 36],
       [34, 67, 38, 70],
       [47, 63, 37, 40]])

In [9]:
np.sort(a)[::-1]

array([61, 61, 61, 61, 59, 59, 58, 58, 56, 55, 55, 53, 52, 50, 50])

In [14]:
np.sort(b,axis=1)

array([[38, 58, 68, 73],
       [25, 30, 41, 61],
       [35, 53, 64, 70],
       [36, 41, 43, 48],
       [34, 38, 67, 70],
       [37, 40, 47, 63]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [19]:
# code
np.append(a,300)

array([ 58,  50,  59,  50,  53,  52,  56,  58,  55,  61,  59,  61,  55,
        61,  61, 300])

In [20]:
b

array([[68, 38, 58, 73],
       [30, 41, 25, 61],
       [53, 64, 35, 70],
       [48, 41, 43, 36],
       [34, 67, 38, 70],
       [47, 63, 37, 40]])

In [21]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[6.80000000e+01, 3.80000000e+01, 5.80000000e+01, 7.30000000e+01,
        2.11867840e-01],
       [3.00000000e+01, 4.10000000e+01, 2.50000000e+01, 6.10000000e+01,
        2.43208599e-02],
       [5.30000000e+01, 6.40000000e+01, 3.50000000e+01, 7.00000000e+01,
        1.39905793e-01],
       [4.80000000e+01, 4.10000000e+01, 4.30000000e+01, 3.60000000e+01,
        9.98013227e-01],
       [3.40000000e+01, 6.70000000e+01, 3.80000000e+01, 7.00000000e+01,
        1.17701480e-01],
       [4.70000000e+01, 6.30000000e+01, 3.70000000e+01, 4.00000000e+01,
        6.91563283e-01]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [22]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [25]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [26]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [27]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [28]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [29]:
# code
a.shape

(15,)

In [30]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [32]:
np.expand_dims(a,axis=1).shape

(15, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [33]:
a

array([58, 50, 59, 50, 53, 52, 56, 58, 55, 61, 59, 61, 55, 61, 61])

In [39]:
# find all indices with value greater than 50
np.where(a>55)

(array([ 0,  2,  6,  7,  9, 10, 11, 13, 14]),)

In [41]:
# replace all values > 50 with 0
np.where(a>55,0,a)

array([ 0, 50,  0, 50, 53, 52,  0,  0, 55,  0,  0,  0, 55,  0,  0])

In [42]:
np.where(a%2 == 0,0,a)

array([ 0,  0, 59,  0, 53,  0,  0,  0, 55, 61, 59, 61, 55, 61, 61])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [43]:
# code
a

array([58, 50, 59, 50, 53, 52, 56, 58, 55, 61, 59, 61, 55, 61, 61])

In [44]:
np.argmax(a)

9

In [45]:
b

array([[68, 38, 58, 73],
       [30, 41, 25, 61],
       [53, 64, 35, 70],
       [48, 41, 43, 36],
       [34, 67, 38, 70],
       [47, 63, 37, 40]])

In [46]:
np.argmax(b,axis=0)

array([0, 4, 0, 0])

In [48]:
np.argmax(b,axis=1)

array([3, 3, 3, 0, 3, 1])

In [ ]:
# np.argmin
np.argmin(a)

13

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [49]:
a

array([58, 50, 59, 50, 53, 52, 56, 58, 55, 61, 59, 61, 55, 61, 61])

In [50]:
np.cumsum(a)

array([ 58, 108, 167, 217, 270, 322, 378, 436, 491, 552, 611, 672, 727,
       788, 849])

In [51]:
b

array([[68, 38, 58, 73],
       [30, 41, 25, 61],
       [53, 64, 35, 70],
       [48, 41, 43, 36],
       [34, 67, 38, 70],
       [47, 63, 37, 40]])

In [52]:
np.cumsum(b,axis=1)

array([[ 68, 106, 164, 237],
       [ 30,  71,  96, 157],
       [ 53, 117, 152, 222],
       [ 48,  89, 132, 168],
       [ 34, 101, 139, 209],
       [ 47, 110, 147, 187]])

In [53]:
np.cumsum(b)

array([  68,  106,  164,  237,  267,  308,  333,  394,  447,  511,  546,
        616,  664,  705,  748,  784,  818,  885,  923,  993, 1040, 1103,
       1140, 1180])

In [54]:
# np.cumprod
np.cumprod(a)

array([                  58,                 2900,               171100,
                    8555000,            453415000,          23577580000,
              1320344480000,       76579979840000,     4211898891200000,
         256925832363200000, -3288119964280751616,  2338866989679219200,
        -489524083609805312,  7032519047220979200,  4708548185160044032])

In [55]:
a

array([58, 50, 59, 50, 53, 52, 56, 58, 55, 61, 59, 61, 55, 61, 61])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [60]:
a

array([58, 50, 59, 50, 53, 52, 56, 58, 55, 61, 59, 61, 55, 61, 61])

In [64]:
np.percentile(a,50)

58.0

In [65]:
np.median(a)

58.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [68]:
# code
a

array([58, 50, 59, 50, 53, 52, 56, 58, 55, 61, 59, 61, 55, 61, 61])

In [69]:
np.histogram(a,bins=[0,50,100]) 

(array([ 0, 15]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [74]:
salary = np.array([20000,50000])
experience = np.array([5,6])

np.corrcoef(salary,experience)

array([[1., 1.],
       [1., 1.]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [75]:
# code
a


array([58, 50, 59, 50, 53, 52, 56, 58, 55, 61, 59, 61, 55, 61, 61])

In [76]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([50, 50])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [77]:
# code
a

array([58, 50, 59, 50, 53, 52, 56, 58, 55, 61, 59, 61, 55, 61, 61])

In [78]:
np.flip(a)

array([61, 61, 55, 61, 59, 61, 55, 58, 56, 52, 53, 50, 59, 50, 58])

In [79]:
b

array([[68, 38, 58, 73],
       [30, 41, 25, 61],
       [53, 64, 35, 70],
       [48, 41, 43, 36],
       [34, 67, 38, 70],
       [47, 63, 37, 40]])

In [80]:
np.flip(b,axis=1)

array([[73, 58, 38, 68],
       [61, 25, 41, 30],
       [70, 35, 64, 53],
       [36, 43, 41, 48],
       [70, 38, 67, 34],
       [40, 37, 63, 47]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [81]:
# code
a

array([58, 50, 59, 50, 53, 52, 56, 58, 55, 61, 59, 61, 55, 61, 61])

In [88]:
np.put(a,[13,14],[110,530])
a

array([110, 530, 110, 530, 110, 530,  56,  58,  55,  61,  59,  61,  55,
       110, 530])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [89]:
# code
a

array([110, 530, 110, 530, 110, 530,  56,  58,  55,  61,  59,  61,  55,
       110, 530])

In [90]:
np.delete(a,[0,2,4])

array([530, 530, 530,  56,  58,  55,  61,  59,  61,  55, 110, 530])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [91]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [92]:
np.intersect1d(m,n)

array([3, 4, 5])

In [93]:
np.setdiff1d(n,m)

array([6, 7])

In [94]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [95]:
m[np.in1d(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [96]:
# code
a

array([110, 530, 110, 530, 110, 530,  56,  58,  55,  61,  59,  61,  55,
       110, 530])

In [97]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 75, 75, 75, 75, 56, 58, 55, 61, 59, 61, 55, 75, 75])