<a href="https://colab.research.google.com/github/shubhs777c/python-practice/blob/main/numpy_fundamentals_basic_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
# dtype
np.array([1,2,3],dtype=float)
np.array([1,2,3],dtype=int)

array([1, 2, 3])

In [10]:
# np.arange
np.arange(1,11,3)

array([ 1,  4,  7, 10])

In [14]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [18]:
# np.ones and np.zeros
np.ones((3,4),dtype=int)
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [29]:
# np.random
np.random.random((5,8))

array([[0.8790787 , 0.46846669, 0.37104051, 0.50523936, 0.94099744,
        0.16060684, 0.27712631, 0.96932776],
       [0.02477315, 0.9830697 , 0.21202964, 0.11656501, 0.41766956,
        0.410434  , 0.70085056, 0.70621047],
       [0.75970938, 0.8261158 , 0.29578696, 0.18549625, 0.93182118,
        0.79008704, 0.02136182, 0.88261586],
       [0.14081935, 0.56053162, 0.51700979, 0.37322376, 0.15985304,
        0.20283782, 0.95358081, 0.59625966],
       [0.41672732, 0.65637314, 0.83334246, 0.83970899, 0.3334475 ,
        0.47860068, 0.94996177, 0.84102403]])

In [31]:
# np.linspace
np.linspace(-10,10,5,dtype=int)

array([-10,  -5,   0,   5,  10])

In [34]:
# np.identity
np.identity(2,dtype=int)

array([[1, 0],
       [0, 1]])

### Array Attributes

In [61]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=int).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
print(a1)
print("*********")
print(a2)
print("*********")
print(a3)

[0 1 2 3 4 5 6 7 8 9]
*********
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
*********
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [62]:
# ndim
a3.ndim

3

In [63]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [64]:
# size
print(a2.size)
a2

12


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
# itemsize
a3.itemsize

8

In [66]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
int64
int64


### Changing Datatype

In [67]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [73]:
a1 = np.arange(12).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
a2 = np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [75]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [76]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [77]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

In [85]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100,)
# a1.dtype=int
a1

array([[85., 73., 57.],
       [11., 36.,  6.],
       [25., 79., 71.]])

In [87]:
# mean/median/std/var
np.var(a1,axis=1)

array([131.55555556, 172.22222222, 566.22222222])

In [88]:
# trigonomoetric functions
np.sin(a1)

array([[-0.17607562, -0.67677196,  0.43616476],
       [-0.99999021, -0.99177885, -0.2794155 ],
       [-0.13235175, -0.44411267,  0.95105465]])

In [89]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [90]:
# log and exponents
np.exp(a1)

array([[8.22301271e+36, 5.05239363e+31, 5.68572000e+24],
       [5.98741417e+04, 4.31123155e+15, 4.03428793e+02],
       [7.20048993e+10, 2.03828107e+34, 6.83767123e+30]])

In [91]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[ 27.,   1.,  15.],
       [100.,  87.,  33.]])

### Indexing and Slicing

In [97]:
a1 = np.arange(10)
a2 = np.arange(9).reshape(3,3)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [93]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
a2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [99]:
a2[1,0]

3

In [100]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [101]:
a3[1,0,1]

5

In [102]:
a3[1,1,0]

6

In [103]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
a1[2:9:2]

array([2, 4, 6, 8])

In [106]:
a2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [110]:
a2[0:2,1:2]

array([[1],
       [4]])

In [114]:
a2[::2,1:2]

array([[1],
       [7]])

In [112]:
a2[1,::3]

array([3])

In [113]:
a2[0,:]

array([0, 1, 2])

In [121]:
a2[:,2]

array([2, 5, 8])

In [122]:
a2[1:,1:3]

array([[4, 5],
       [7, 8]])

In [123]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [124]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [125]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [126]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [127]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [128]:
a2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [129]:
for i in a2:
  print(i)

[0 1 2]
[3 4 5]
[6 7 8]


In [130]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [131]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [132]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [133]:
# reshape

In [134]:
# Transpose
np.transpose(a2)
a2.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [135]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [138]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [139]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [137]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [141]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [142]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# vertical splitting

In [144]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])