<a href="https://colab.research.google.com/github/shubhs777c/code-for-help/blob/main/ppb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
abc=[1,2,3,'xyz','pqr']
tuple1=tuple(abc)
print(tuple1)

In [ ]:
a=72
if a>=85:
   print ("a grade")
elif (a<85) and (a>=80):
   print("a- grade")
elif a<80 and a>=75:
   print("b grade")
elif a<75 and a>=70:
  print("b-grade")
else:
  print ("below average")


b-grade


In [ ]:
a= 50
b= 20
if a>b :
  print("b is greater than a")
elif a==b:
  print("a and b are equal")
else:
  print("a is greater than b")

b is greater than a


In [ ]:
a= 10
b= 20
print("a") if a > b else print ("=") if a==b else print("b")

b


In [ ]:
x=10
if x>10:
  print("your number is above 10")
if x>20:
  print("and also above 20")
else:
  print("but not above 20")

but not above 20


In [ ]:
a= 50
if a>10:
  print(">10")
  if a>20:
    print("20")
    print ("inside the nested if")
else:
  print("<=20")
  print("inside the else part of nested if")
  print("outside all ifs")

>10
20
inside the nested if


In [ ]:
n= 5
i=2
while i<n:
  print(i)
  i+=1
  print ("done")

2
done
3
done
4
done


In [ ]:
n=10
i==1
while i<n:
  print(i**2)
  print("this is iteration number",i)
  i+=1
  print("loop done")

In [ ]:
n=10
i=1
while i<n:
 if i%2== 0:
  print(i)
else:
    pass
i+=1
print(done)

In [ ]:
i=1
while True:
  if i%17==0:
   print("break")
  break
else:
  i+=1
   continue
  print('i am inside the loop')
  print(done)

IndentationError: ignored

In [ ]:
n=10
i=1
while True:
  if i%9==0:
    print("inside if")
    break
else:
    print("inside else")
    i=i+1
    print(done)

In [ ]:
n=10
i=1
while True:
  if i%9!=0:
    print("inside if")
    i+=1
    continue
    print("something")
    print("something else")
    break

print("done")


In [ ]:
print(abs(9.35))

9.35


In [ ]:
x=2
y=3
print(pow(x,y))

8


In [ ]:
import math
print(math.sqrt(81))
print(math.ceil(2.35))
print(math.floor(2.35))
print(math.pi)
print(math.factorial(12))
print(math.sin(90))

9.0
3
2
3.141592653589793
479001600
0.8939966636005579


In [ ]:
l=[]
for i in range (0,10):
 print(i)
 l.append(i**2)
 print(l)


0
[0]
1
[0, 1]
2
[0, 1, 4]
3
[0, 1, 4, 9]
4
[0, 1, 4, 9, 16]
5
[0, 1, 4, 9, 16, 25]
6
[0, 1, 4, 9, 16, 25, 36]
7
[0, 1, 4, 9, 16, 25, 36, 49]
8
[0, 1, 4, 9, 16, 25, 36, 49, 64]
9
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
s={"apple",4.9,"cherry"}
for x in s:
  print(x)
else:
  print('loop complete its iterations')

4.9
apple
cherry
loop complete its iterations


In [ ]:
s={"apple",4.9,"cherry"}
i=1
for x in s:
  print(x)
  i+=1
if i==3:
      break
else:
    pass

4.9
apple
cherry


SyntaxError: ignored

In [ ]:
d={"a":10,"b":-19,"c":"abc"}
for x in d:
 print(x,d[x])

a 10
b -19
c abc


In [ ]:
l=[1,2,4,-5,7,9,3,2]
l.sort()
print(l)

[-5, 1, 2, 2, 3, 4, 7, 9]


In [ ]:
def print_success():
  print("i am done")
  print("send me another task")
print_success()

i am done
send me another task


In [ ]:
def my_pow(a,b):
  c=a**b
  print(c)
my_pow(3,4)


81


In [ ]:
def f(a,b,c):
  print("a is:" ,'a')
  print("b is:" ,'b')
  print("c is:" ,'c')
  f(a,b,c)

In [ ]:
def add(x,y):
  c= x + y
  print(c)
add(3,4)


7


In [ ]:
def my_add (a,b):
   d=a+b
   print(d)
my_add(2,3)

5


In [ ]:
variableoutsidethefunction =3 
def g ():
   variableoutsidethefunction =5 
   print(variableoutsidethefunction)
g()
print(variableoutsidethefunction)

5
3


In [ ]:
def r():
 a=5
 b=7
 d="something"
 return a,b,d
print(x,y,z)


5 7 something


In [ ]:
#function(variable_no_of_input_arguments)
def my_add_universal (*args):
  s=0
for i in range (len(args)):
  s+=args[i]
return (s)
print (my_add_universal)(2,4,5,4.6,7,8)

NameError: ignored

In [ ]:
def printallvariablenamesandvalues(**args):
  for x in args:
    print("variablenameis:",x," and value is :",args[x])
printallvariablenamesandvalues(a=3,b="B",c="ccc",y=6.7)

variablenameis: a  and value is : 3
variablenameis: b  and value is : B
variablenameis: c  and value is : ccc
variablenameis: y  and value is : 6.7


In [ ]:
s="python is good language "
t= "it is good for data science"
v=s+t
print(v)

python is good language it is good for data science


In [ ]:
"python is good language "
"it is good for data science"
add="python is good language "+"it is good for data science"
print(add)

python is good language it is good for data science


In [ ]:
a='game of programming'
print(a[3:8])
print(a[-8:-3])

e of 
gramm


In [ ]:
s= 'how are you and who are you'
print(s[5])
print(s[3:8])
print(s[-12:-3])
print(s[0:12:2])
print(s[3:])
print(s[1:12])


r
 are 
 who are 
hwaeyu
 are you and who are you
ow are you 


In [ ]:
l=[1,3,4.9,"name",3]
t=(1,3,4.9,"name",3)
s={1,3,4.9,"name",3}
l=l+["how","are","you"]
print(l)
t2=('a','b',45)
t3=t+t2
print(t3)
print(s)
s.add(56)
print(s)
s.update({23,"game",1})
print(s)
d={23:"twothree",'B':43,'c':'ccd'}
print(d)
d['newkey']="newvalue"
print(d)
s.remove('game')
print(s)
del d['c']
print (d)
l.reverse()
print(l)
l[::-1]
print(l)
d.items()
print(d)


[1, 3, 4.9, 'name', 3, 'how', 'are', 'you']
(1, 3, 4.9, 'name', 3, 'a', 'b', 45)
{1, 3, 4.9, 'name'}
{1, 3, 4.9, 'name', 56}
{1, 3, 4.9, 'name', 'game', 23, 56}
{23: 'twothree', 'B': 43, 'c': 'ccd'}
{23: 'twothree', 'B': 43, 'c': 'ccd', 'newkey': 'newvalue'}
{1, 3, 4.9, 'name', 23, 56}
{23: 'twothree', 'B': 43, 'newkey': 'newvalue'}
['you', 'are', 'how', 3, 'name', 4.9, 3, 1]
['you', 'are', 'how', 3, 'name', 4.9, 3, 1]
{23: 'twothree', 'B': 43, 'newkey': 'newvalue'}


{23: 'twothree', 'B': 43, 'c': 'ccd'}


In [ ]:
l3=[x ** 2 for x in range (10)]
print(l3)
s3={x**2 for x in range (2,20,3)}
print(s3)



[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
{64, 121, 289, 196, 4, 25}


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([1,6,3,4,9])
print(a)
print(b)

[1 2 3 4 5]
[1 6 3 4 9]


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
a.ndim
a[0,2]
a.size
a=np.arrange(100)
print(a)

AttributeError: ignored

In [ ]:
import numpy as np
print(list(range(10)))
a=np.random.permutation(np.arrange(10))
print(a)



[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


AttributeError: ignored

In [ ]:
import numpy as np
A=np.round(10*np.random.rand(5,4))
print(A)
A[:,1]
b=a[(a<40)& (a>30)]
b

[[ 4.  4.  7.  3.]
 [ 6.  5.  5.  3.]
 [ 2.  3.  2. 10.]
 [ 8.  2.  5.  3.]
 [ 2.  7.  6.  3.]]


array([], dtype=int64)

In [ ]:
b=a[(a<40)& (a>30)]
print(b)

[]


In [ ]:
import pandas as pd
print(pd._version_)


AttributeError: ignored

In [ ]:
a=pd.series([2,3,4,5],index=['a','b','c','d'])
a.values

In [ ]:
import pandas as pd
marks_dict={'a':85,'b':75,'c':65,'d':55}
marks=pd.series(marks_dict)
print(marks)

AttributeError: ignored

In [ ]:
s="shubham "
result="".join(reversed(s))
print(result)



 mahbuhs


In [ ]:
bikes = ['splendor', 'pulsar']
cars = ['alto', 'indigo']
df["cars"]=cars
df["bikes"]= bikes
print(df)

NameError: ignored

In [ ]:
mylist=['x','y','z','z','s']
mylist=list(dict.fromkeys(mylist))
print(mylist)

['x', 'y', 'z', 's']


In [ ]:
list=[i for i in range(1000)]
print(list)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

In [ ]:
list=["abcd"]
n=letters.split(",")
print(n)

NameError: ignored

In [ ]:
triple=lambda x :x**3
print(triple(5))

125


In [ ]:
def factorial (a):
      if a==1:
       return 1
      else:
          return(a* factorial(a-1))
input_number=5
print("the factorial of" ,input_number ,"is",factorial(input_number))


the factorial of 5 is 120


In [ ]:
from string import digits
#to check the logic the no is palindrome or not
n=int(input("enter number:"))
temp=n
rev=0
while(n>0):
  dig=n%10
  rev=rev*10+dig
  
  n=n//10
  if(temp==rev):
    print("the number isa palindrome")
  else:
    print("the number is not a palindrome")

enter number:111111111111
the number is not a palindrome
the number is not a palindrome
the number is not a palindrome
the number is not a palindrome
the number is not a palindrome
the number is not a palindrome
the number is not a palindrome
the number is not a palindrome
the number is not a palindrome
the number is not a palindrome
the number is not a palindrome
the number isa palindrome


In [ ]:
for inp_num in range(6):
  for i in range(inp_num):
    print(inp_num,end=" ")
print("n\")


SyntaxError: ignored

In [ ]:
d1={"k1":10 ,"k2":20,"k3":30}
for i in d1.keys():
   d1[i]=d1[i]+1
d1.values()

dict_values([11, 21, 31])

In [ ]:
def check_pass(arr):
  arr.append(4)
arr=[1,2,3]
print(arr)
check_pass(arr)
print(arr)

[1, 2, 3]
[1, 2, 3, 4]


In [ ]:
list1=[1,2,3,4,5]
list1*5


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
sample_list=[10,20,30,40,50]
def swap_func (sample_list)
size=len(sample_list)

In [ ]:
def swap():
    global A
    A = [A[len(A)-1]]+A[1:len(A)-1]+[A[0]]
    
A=[1,2,3,4]
swap()

In [ ]:
#public static boolean istPalindrom(char[] word){
int i1 = 15;
    int i2 = word.length - 1;
    while (i2 > i1) {
        if (word[i1] != word[i2]) {
            return false;
        }
        ++i1;
        --i2;
    }
    return true;
}


SyntaxError: ignored

In [ ]:
function getVowels(str) {
  var m = str.match(/[aeiou]/gi);
  return m === null ? 0 : m.length;
}

SyntaxError: ignored

In [ ]:
for num in range (100,200):
 if all (num%!=0) for i in range(2,num)):
    print(num)


SyntaxError: ignored

In [ ]:
list=[21,1,34,5,6,7,819,3,4,36,48,50,51]
def rev[1]
   return l[::-1]
rev[list]

SyntaxError: ignored

In [ ]:
list=[1,2,3,4,4,5,5,6,1]
print(set([x for x in list if list.count (x)>1]))

{1, 4, 5}


In [ ]:
def_init_(self,fname,lname,age,section):
  self.firstname=fname
  self.lastname=lname
  self.age=age
  self.section=section
  stud1=student("sara","ansh",'22',"a2")
  student1.print_student()

SyntaxError: ignored

In [ ]:
for val in "string":
  if val=="i" :
break
print (val)
  print("the end")

IndentationError: ignored

In [ ]:
string="this is a string"
string_list=string.split()
print(string_list)

['this', 'is', 'a', 'string']


In [ ]:
print(" ".join (string_list))


this is a string


In [ ]:
import numpy as np
x=np.array([4,5,6,7,8])
type(x)
x.size


5

In [ ]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
x=np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [ ]:
x.shape

(2, 3)

In [ ]:
x.dtype

dtype('int64')

In [ ]:
np.ones((5,6))


array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.empty(4)

array([5.e-324, 5.e-324, 5.e-324, 0.e+000])

In [ ]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
np.identify(5)

AttributeError: ignored

In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
x=np.arange(10)
x[x%2==1]


array([1, 3, 5, 7, 9])

In [ ]:
a=np.array([1,2,3,4])
a**2
print(a)

[1 2 3 4]


In [ ]:
import pandas as pd
dt={'fruit_name':["apple","mango","orange"],'count':[12,24,36]}
pd.dataframe(dt)

AttributeError: ignored

In [ ]:
"ophthamology"
count=0
for i in a:
  count=count+1
print (count)

4


In [ ]:
list1=[1,2,54,5,8,8,9,6,7,2,5,4,6,6,9,1]
for i in range (n):
  for j in range(i+1,n):
   if list1[i]>list1[j]:
     list1[i],list1[j]=list1[j],list1[j]
print(list1)


[1, 2, 5, 5, 6, 6, 6, 6, 7, 2, 5, 4, 6, 6, 9, 1]


In [ ]:
s="nitin"
if s==s[::-1]:
   print("yes palindrome")
else:
  print("no")


yes palindrome


In [ ]:
s="nitin"

x=5
for i in range(n):
  if s[i]!=s[n-i-1]:
    x=1
    break
  if x==5:
      print("yes_palindrome")
else:
     print("no")


yes_palindrome
yes_palindrome
yes_palindrome
yes_palindrome
yes_palindrome
no


In [ ]:
dict